// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace MechGameplayTags
{
	/** Input Tags **/
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump); 
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipPunch);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipPunch);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Punch); 
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Punch); 
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	
	/** Player Tags **/
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Punch);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Punch);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Punch);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Punch);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Punch);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_PunchSecondary);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Punch);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Punch);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/** Enemy Tags **/
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SummonEnemies);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_WeaponSecondary);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_WeaponMouth);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_SummonEnemies);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_BossUI);
	
	/** Shared tags **/
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	PALACEMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);

}
